public with sharing class Acccretion {
    public list<Account> Acccretion() {
        list<Account> acclist =[select id,name,AnnualRevenue,AccountSource from Account];
        return acclist;
    
    }

     public list<Account> Acccretion() {
        list<Account> acclist =[select id,name,AnnualRevenue,AccountSource from Account];
        return acclist;
}
    public sttic sl(){
        return 'hello';}

 public sttic sl(){
        return 'hi';}

         public sttic sl(){
        return 'hi';}


}